# Generated by Django 5.1.15 on 2026-08-08 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_identidad_plazas_sesiones'),
        ('saas_core', '0001_saas_multitenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='institucion',
            field=models.ForeignKey(blank=True, help_text='Institución (tenant). Obligatorio salvo SuperAdmin SaaS.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='saas_core.institucion'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN_SAAS', 'SuperAdmin SaaS (Plataforma)'), ('ADMIN_SISTEMA', 'Administrador de Institución'), ('VISOR_EJECUTIVO', 'Visor Ejecutivo (Alto Mando)'), ('DIRECTOR_ZONA', 'Director / Jefe de Zona'), ('SUPERVISOR_UNIDAD', 'Supervisor de Unidad'), ('DETECTIVE', 'Detective / Investigador'), ('AGENTE_OPERATIVO', 'Agente Operativo')], max_length=32),
        ),
    ]
