# Generated by Django 5.1.15 on 2026-08-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_plataforma_acceso'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_url',
            field=models.CharField(blank=True, help_text='URL/proxy de foto de perfil (MinIO).', max_length=500),
        ),
    ]
