# Generated by Django 5.1.15 on 2026-08-08 05:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('BASICO', 'Plan Básico'), ('CORPORATIVO', 'Plan Corporativo'), ('GUBERNAMENTAL', 'Plan Gubernamental')], default='BASICO', max_length=32, unique=True)),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.TextField(blank=True)),
                ('audiencia', models.CharField(blank=True, help_text='Ej. Metropolitana/Municipal, Seguridad Privada, Enterprise', max_length=120)),
                ('precio_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('limite_usuarios', models.PositiveIntegerField(default=25)),
                ('almacenamiento_gb', models.PositiveIntegerField(default=50, help_text='Cuota MinIO (GB)')),
                ('tiene_analitica_avanzada', models.BooleanField(default=False, help_text='Analítica ClickHouse avanzada')),
                ('on_premise', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Plan de suscripción',
                'verbose_name_plural': 'Planes de suscripción',
                'ordering': ['orden', 'precio_mensual'],
            },
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(max_length=180)),
                ('ruc', models.CharField(max_length=32, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('esta_activa', models.BooleanField(default=True)),
                ('estado_pago', models.CharField(choices=[('ACTIVO', 'Activo'), ('SUSPENDIDO', 'Suspendido por falta de pago'), ('PRUEBA', 'Prueba gratuita'), ('CANCELADO', 'Cancelado')], default='PRUEBA', max_length=20)),
                ('metodo_facturacion', models.CharField(blank=True, default='tarjeta', help_text='tarjeta | transferencia | orden_compra', max_length=40)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('admin_institucional', models.ForeignKey(blank=True, help_text='Master Admin (rol ADMIN_SISTEMA) de esta institución', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instituciones_administradas', to=settings.AUTH_USER_MODEL)),
                ('plan_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instituciones', to='saas_core.plansuscripcion')),
            ],
            options={
                'verbose_name': 'Institución (Tenant)',
                'verbose_name_plural': 'Instituciones (Tenants)',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
