# Generated by Django 5.1.15 on 2026-08-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodelito',
            name='clasificacion_fbi',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='tipodelito',
            name='codigo_iucr',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
