# Generated by Django 5.1.15 on 2026-08-01 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NovedadIncidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('lugar', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('CHOQUE_LEVE', 'Choque leve'), ('RINA', 'Riña callejera'), ('AUXILIO_MEDICO', 'Auxilio médico'), ('OTRO', 'Otro incidente')], max_length=40)),
                ('descripcion', models.TextField()),
                ('hubo_detenidos', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='novedades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Novedad / incidente',
                'verbose_name_plural': 'Novedades e incidentes',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='ParteAprehension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('lugar', models.CharField(max_length=255)),
                ('detenido_nombres', models.CharField(max_length=150)),
                ('detenido_apellidos', models.CharField(max_length=150)),
                ('detenido_cedula', models.CharField(blank=True, max_length=20)),
                ('detenido_edad', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('relato_hechos', models.TextField()),
                ('derechos_leidos', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partes_aprehension', to=settings.AUTH_USER_MODEL)),
                ('tipo_delito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partes', to='catalogos.tipodelito')),
            ],
            options={
                'verbose_name': 'Parte de aprehensión',
                'verbose_name_plural': 'Partes de aprehensión',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='MultimediaEvidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('PARTE', 'Parte de aprehensión'), ('NOVEDAD', 'Novedad / incidente'), ('RAPIDA', 'Captura rápida en calle')], default='RAPIDA', max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('tamanio_bytes', models.PositiveIntegerField(default=0)),
                ('bucket', models.CharField(default='', max_length=120)),
                ('object_key', models.CharField(max_length=512)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidencias_multimedia', to=settings.AUTH_USER_MODEL)),
                ('novedad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multimedia', to='operativo.novedadincidente')),
                ('parte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multimedia', to='operativo.parteaprehension')),
            ],
            options={
                'verbose_name': 'Evidencia multimedia',
                'verbose_name_plural': 'Evidencias multimedia',
                'ordering': ['-creado_en'],
            },
        ),
    ]
