# Generated by Django 5.1.15 on 2026-08-01 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operativo', '0001_initial'),
        ('organizacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('descripcion', models.TextField(blank=True)),
                ('direccion', models.CharField(max_length=255)),
                ('referencia', models.CharField(blank=True, max_length=255)),
                ('origen', models.CharField(default='ECU-911', max_length=40)),
                ('prioridad', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='ALTA', max_length=10)),
                ('estado', models.CharField(choices=[('ASIGNADA', 'Asignada'), ('EN_CAMINO', 'En camino'), ('EN_LUGAR', 'En el lugar'), ('CERRADA', 'Cerrada'), ('CANCELADA', 'Cancelada')], default='ASIGNADA', max_length=20)),
                ('asignada_en', models.DateTimeField(auto_now_add=True)),
                ('en_camino_en', models.DateTimeField(blank=True, null=True)),
                ('llegada_en', models.DateTimeField(blank=True, null=True)),
                ('cerrada_en', models.DateTimeField(blank=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alertas_despacho', to=settings.AUTH_USER_MODEL)),
                ('asignada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta de despacho',
                'verbose_name_plural': 'Alertas de despacho',
                'ordering': ['-asignada_en'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('vehiculo_placa', models.CharField(max_length=20)),
                ('vehiculo_tipo', models.CharField(default='Patrulla', max_length=60)),
                ('cuadrante', models.CharField(max_length=120)),
                ('turno_inicio', models.TimeField()),
                ('turno_fin', models.TimeField()),
                ('observaciones', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_diarias', to=settings.AUTH_USER_MODEL)),
                ('companero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_como_companero', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_supervisadas', to=settings.AUTH_USER_MODEL)),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_patrulla', to='organizacion.jurisdiction')),
            ],
            options={
                'verbose_name': 'Asignación diaria',
                'verbose_name_plural': 'Asignaciones diarias',
                'ordering': ['-fecha', '-creado_en'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('agente', 'fecha'), name='uniq_asignacion_activa_agente_fecha')],
            },
        ),
    ]
