# Generated by Django 5.1.15 on 2026-08-01 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operativo', '0002_alertadespacho_asignaciondiaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertadespacho',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='alertadespacho',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='asignaciondiaria',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='asignaciondiaria',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='asignaciondiaria',
            name='unidad_label',
            field=models.CharField(default='Unidad móvil', max_length=80),
        ),
        migrations.AddField(
            model_name='parteaprehension',
            name='alerta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partes', to='operativo.alertadespacho'),
        ),
        migrations.AddField(
            model_name='parteaprehension',
            name='enviado_revision_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parteaprehension',
            name='estado_revision',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_REVISION', 'Pendiente de revisión'), ('OBSERVADO', 'Observado'), ('APROBADO', 'Aprobado')], default='BORRADOR', max_length=20),
        ),
    ]
