# Generated by Django 5.1.15 on 2026-08-01 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operativo', '0003_alertadespacho_latitud_alertadespacho_longitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parteaprehension',
            name='clasificacion_fbi',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='parteaprehension',
            name='codigo_iucr',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='parteaprehension',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parteaprehension',
            name='estado_inicial',
            field=models.CharField(default='Clasificado', max_length=40),
        ),
        migrations.AddField(
            model_name='parteaprehension',
            name='fecha_hecho',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parteaprehension',
            name='fuente_reporte',
            field=models.CharField(choices=[('LLAMADA_911', 'Llamada 911'), ('DENUNCIA_PRESENCIAL', 'Denuncia presencial'), ('PATRULLAJE', 'Patrullaje'), ('SUPERVISOR', 'Asignación de supervisor'), ('OTRO', 'Otro')], default='LLAMADA_911', max_length=40),
        ),
        migrations.AddField(
            model_name='parteaprehension',
            name='hay_armas',
            field=models.CharField(choices=[('SI', 'Sí'), ('NO', 'No'), ('DESCONOCIDO', 'Desconocido')], default='DESCONOCIDO', max_length=20),
        ),
        migrations.AddField(
            model_name='parteaprehension',
            name='hay_heridos',
            field=models.CharField(choices=[('SI', 'Sí'), ('NO', 'No'), ('DESCONOCIDO', 'Desconocido')], default='DESCONOCIDO', max_length=20),
        ),
        migrations.AddField(
            model_name='parteaprehension',
            name='hora_hecho',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parteaprehension',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='parteaprehension',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='parteaprehension',
            name='nivel_riesgo',
            field=models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto')], default='MEDIO', max_length=20),
        ),
        migrations.AddField(
            model_name='parteaprehension',
            name='numero_caso',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='parteaprehension',
            name='prioridad',
            field=models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=20),
        ),
        migrations.AddField(
            model_name='parteaprehension',
            name='sector_zona',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='parteaprehension',
            name='titulo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='parteaprehension',
            name='detenido_apellidos',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='parteaprehension',
            name='detenido_nombres',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='parteaprehension',
            name='relato_hechos',
            field=models.TextField(blank=True),
        ),
    ]
