# Generated by Django 5.1.15 on 2026-08-01 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operativo', '0004_parteaprehension_clasificacion_fbi_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parteaprehension',
            name='aprobado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parteaprehension',
            name='bloqueado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parteaprehension',
            name='motivo_rechazo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parteaprehension',
            name='pdf_bucket',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='parteaprehension',
            name='pdf_object_key',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='parteaprehension',
            name='rechazado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parteaprehension',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partes_revisados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parteaprehension',
            name='estado_revision',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_REVISION', 'Pendiente de revisión'), ('OBSERVADO', 'Rechazado'), ('APROBADO', 'Aprobado')], default='BORRADOR', max_length=20),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PARTE_RECHAZADO', 'Parte rechazado'), ('PARTE_APROBADO', 'Parte aprobado'), ('ALERTA', 'Alerta'), ('SISTEMA', 'Sistema')], default='SISTEMA', max_length=40)),
                ('titulo', models.CharField(max_length=180)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('enlace', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('leida_en', models.DateTimeField(blank=True, null=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
                ('parte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='operativo.parteaprehension')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-creado_en'],
            },
        ),
    ]
