# Generated by Django 5.1.15 on 2026-08-01 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operativo', '0005_parteaprehension_aprobado_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiculoFlota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('PATRULLA', 'Patrullero'), ('MOTO', 'Motocicleta'), ('OTRO', 'Otro')], default='PATRULLA', max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=160)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vehículo de flota',
                'verbose_name_plural': 'Vehículos de flota',
                'ordering': ['placa'],
            },
        ),
        migrations.AddField(
            model_name='asignaciondiaria',
            name='hora_formacion_real',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asignaciondiaria',
            name='hora_salida_real',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asignaciondiaria',
            name='sector_detalle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='Escuadra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('fecha', models.DateField()),
                ('observaciones', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('agente_companero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escuadras_como_companero', to=settings.AUTH_USER_MODEL)),
                ('agente_lider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escuadras_como_lider', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escuadras_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Escuadra',
                'verbose_name_plural': 'Escuadras',
                'ordering': ['-fecha', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='asignaciondiaria',
            name='escuadra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones', to='operativo.escuadra'),
        ),
        migrations.CreateModel(
            name='GestionHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('CAMBIO_TURNO', 'Cambio de turno'), ('FORMACION', 'Formación / salida'), ('PERMISO_MEDICO', 'Permiso médico'), ('AUSENCIA', 'Ausencia corta'), ('OTRO', 'Otro')], max_length=30)),
                ('detalle', models.TextField()),
                ('hora_formacion', models.TimeField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('respuesta', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gestiones_horario', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestiones_horario_revisadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gestión de horario',
                'verbose_name_plural': 'Gestiones de horario',
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
        migrations.AddField(
            model_name='asignaciondiaria',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones', to='operativo.vehiculoflota'),
        ),
    ]
