# Generated by Django 5.1.15 on 2026-08-01 06:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operativo', '0006_flota_escuadras_horarios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escuadra',
            name='agente_companero',
        ),
        migrations.AddField(
            model_name='escuadra',
            name='companeros',
            field=models.ManyToManyField(blank=True, related_name='escuadras_como_companero', to=settings.AUTH_USER_MODEL),
        ),
    ]
