# Generated by Django 5.1.15 on 2026-08-01 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operativo', '0007_escuadra_multi_companeros'),
    ]

    operations = [
        migrations.AddField(
            model_name='escuadra',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escuadras', to='operativo.vehiculoflota'),
        ),
    ]
