# Generated by Django 5.1.15 on 2026-08-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operativo', '0008_escuadra_vehiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculoflota',
            name='tipo',
            field=models.CharField(choices=[('AUTOMOVIL', 'Automóvil'), ('CAMIONETA', 'Camioneta'), ('MOTO', 'Motocicleta'), ('BLINDADO', 'Blindado'), ('FURGON', 'Furgón'), ('HELICOPTERO', 'Helicóptero'), ('PATRULLA', 'Patrullero'), ('OTRO', 'Otro')], default='AUTOMOVIL', max_length=20),
        ),
    ]
