# Generated by Django 5.1.15 on 2026-08-01 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operativo', '0009_vehiculo_tipos_catalogo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertadespacho',
            name='agente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alertas_despacho', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alertadespacho',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de asignación'), ('ASIGNADA', 'Asignada'), ('EN_CAMINO', 'En camino'), ('EN_LUGAR', 'En el lugar'), ('CERRADA', 'Cerrada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20),
        ),
        migrations.CreateModel(
            name='OrdenAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CUSTODIA', 'Custodia de detenido'), ('TRASLADO_EVIDENCIA', 'Traslado de evidencias'), ('APOYO', 'Apoyo operativo'), ('OTRO', 'Otro')], default='OTRO', max_length=30)),
                ('titulo', models.CharField(max_length=180)),
                ('detalle', models.TextField()),
                ('lugar', models.CharField(blank=True, max_length=255)),
                ('prioridad', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='MEDIA', max_length=10)),
                ('estado', models.CharField(choices=[('ASIGNADA', 'Asignada'), ('EN_CURSO', 'En curso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='ASIGNADA', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('completada_en', models.DateTimeField(blank=True, null=True)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_adicionales', to=settings.AUTH_USER_MODEL)),
                ('asignada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden adicional',
                'verbose_name_plural': 'Órdenes adicionales',
                'ordering': ['-creado_en'],
            },
        ),
    ]
