# Generated by Django 5.1.15 on 2026-08-02 01:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_tipodelito_clasificacion_fbi_tipodelito_codigo_iucr'),
        ('operativo', '0010_despacho_pendiente_ordenes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpedienteCaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_expediente', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('INDAGACION_PREVIA', 'En Indagación Previa'), ('INSTRUCCION_FISCAL', 'En Instrucción Fiscal'), ('CERRADO', 'Cerrado'), ('SUSPENDIDO', 'Suspendido')], default='INDAGACION_PREVIA', max_length=30)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=20)),
                ('fecha_hechos', models.DateField(blank=True, null=True)),
                ('lugar', models.CharField(blank=True, max_length=255)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('detective_asignado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expedientes_asignados', to=settings.AUTH_USER_MODEL)),
                ('jefe_asignador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedientes_asignados_por', to=settings.AUTH_USER_MODEL)),
                ('tipo_delito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedientes', to='catalogos.tipodelito')),
            ],
            options={
                'verbose_name': 'Expediente / caso',
                'verbose_name_plural': 'Expedientes / casos',
                'ordering': ['-actualizado_en'],
            },
        ),
        migrations.CreateModel(
            name='EvidenciaCaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DIGITAL', 'Evidencia digital'), ('FISICA', 'Evidencia física')], max_length=20)),
                ('codigo', models.CharField(blank=True, max_length=40)),
                ('descripcion', models.TextField()),
                ('nombre_archivo', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('tamanio_bytes', models.PositiveIntegerField(default=0)),
                ('bucket', models.CharField(blank=True, max_length=120)),
                ('object_key', models.CharField(blank=True, max_length=512)),
                ('categoria_fisica', models.CharField(blank=True, choices=[('ARMA', 'Arma'), ('DROGA', 'Droga'), ('VEHICULO', 'Vehículo'), ('CELULAR', 'Celular'), ('DOCUMENTO', 'Documento'), ('OTRO', 'Otro')], max_length=20)),
                ('numero_serie', models.CharField(blank=True, max_length=120)),
                ('peso', models.CharField(blank=True, max_length=60)),
                ('caracteristicas', models.TextField(blank=True)),
                ('custodio_actual', models.CharField(blank=True, max_length=200)),
                ('ubicacion_actual', models.CharField(blank=True, max_length=200)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidencias_registradas', to=settings.AUTH_USER_MODEL)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='operativo.expedientecaso')),
            ],
            options={
                'verbose_name': 'Evidencia de caso',
                'verbose_name_plural': 'Evidencias de caso',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='InvolucradoExpediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SOSPECHOSO', 'Sospechoso'), ('VICTIMA', 'Víctima'), ('DENUNCIANTE', 'Denunciante'), ('TESTIGO', 'Testigo')], max_length=20)),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(blank=True, max_length=150)),
                ('cedula', models.CharField(blank=True, max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='involucrados', to='operativo.expedientecaso')),
            ],
            options={
                'verbose_name': 'Involucrado de expediente',
                'verbose_name_plural': 'Involucrados de expediente',
                'ordering': ['tipo', 'apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCustodia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entregado_por', models.CharField(max_length=200)),
                ('recibido_por', models.CharField(max_length=200)),
                ('destino', models.CharField(max_length=200)),
                ('motivo', models.CharField(max_length=255)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('evidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='operativo.evidenciacaso')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_custodia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de custodia',
                'verbose_name_plural': 'Movimientos de custodia',
                'ordering': ['-fecha_hora', '-id'],
            },
        ),
    ]
