# Generated by Django 5.1.15 on 2026-08-02 02:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operativo', '0011_expedientes_evidencias_detective'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expedientecaso',
            name='bloqueado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expedientecaso',
            name='cerrado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expedientecaso',
            name='documento_base',
            field=models.TextField(blank=True, help_text='Texto del parte aprobado o denuncia ciudadana que abre el caso.'),
        ),
        migrations.AddField(
            model_name='expedientecaso',
            name='origen_documento',
            field=models.CharField(choices=[('PARTE_APREHENSION', 'Parte de aprehensión'), ('DENUNCIA_CIUDADANA', 'Denuncia ciudadana (Fiscalía)'), ('OTRO', 'Otro')], default='DENUNCIA_CIUDADANA', max_length=30),
        ),
        migrations.AddField(
            model_name='expedientecaso',
            name='parte_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedientes', to='operativo.parteaprehension'),
        ),
        migrations.AlterField(
            model_name='expedientecaso',
            name='estado',
            field=models.CharField(choices=[('INDAGACION_PREVIA', 'En Indagación Previa'), ('INSTRUCCION_FISCAL', 'En Instrucción Fiscal'), ('CERRADO', 'Cerrado / Enviado a Fiscalía'), ('SUSPENDIDO', 'Suspendido')], default='INDAGACION_PREVIA', max_length=30),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('PARTE_RECHAZADO', 'Parte rechazado'), ('PARTE_APROBADO', 'Parte aprobado'), ('EXPEDIENTE_ASIGNADO', 'Expediente asignado'), ('ALERTA', 'Alerta'), ('SISTEMA', 'Sistema')], default='SISTEMA', max_length=40),
        ),
        migrations.CreateModel(
            name='BienInvestigado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VEHICULO', 'Vehículo'), ('INMUEBLE', 'Inmueble'), ('OTRO', 'Otro')], max_length=20)),
                ('identificador', models.CharField(help_text='Placa, matrícula, dirección catastral, etc.', max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bienes', to='operativo.expedientecaso')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bienes_investigados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bien investigado',
                'verbose_name_plural': 'Bienes investigados',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='BitacoraInvestigacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VIGILANCIA', 'Vigilancia'), ('ENTREVISTA', 'Entrevista a testigo'), ('DILIGENCIA', 'Diligencia de campo'), ('ANALISIS', 'Análisis documental'), ('OTRO', 'Otro')], default='DILIGENCIA', max_length=20)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('lugar', models.CharField(blank=True, max_length=255)),
                ('relato', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacora', to='operativo.expedientecaso')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bitacoras_investigacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrada de bitácora',
                'verbose_name_plural': 'Bitácora de investigación',
                'ordering': ['-fecha_hora', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InformeInvestigativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Informe Investigativo Final', max_length=200)),
                ('contenido', models.TextField()),
                ('conclusiones', models.TextField(blank=True)),
                ('paquete_bucket', models.CharField(blank=True, max_length=120)),
                ('paquete_object_key', models.CharField(blank=True, max_length=512)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('elaborado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='informes_investigativos', to=settings.AUTH_USER_MODEL)),
                ('expediente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='informe_final', to='operativo.expedientecaso')),
            ],
            options={
                'verbose_name': 'Informe investigativo',
                'verbose_name_plural': 'Informes investigativos',
            },
        ),
        migrations.CreateModel(
            name='SolicitudFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ALLANAMIENTO', 'Orden de allanamiento'), ('INTERCEPTACION', 'Interceptación de llamadas'), ('SIGILO_BANCARIO', 'Levantamiento de sigilo bancario'), ('OTRO', 'Otra solicitud')], max_length=30)),
                ('numero', models.CharField(blank=True, max_length=40)),
                ('fundamento', models.TextField()),
                ('pedimento', models.TextField(help_text='Texto formal de lo que se solicita al juez/fiscal.')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada a Fiscalía'), ('RESPONDIDA', 'Respondida')], default='BORRADOR', max_length=20)),
                ('enviado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_fiscal', to=settings.AUTH_USER_MODEL)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_fiscal', to='operativo.expedientecaso')),
            ],
            options={
                'verbose_name': 'Solicitud a Fiscalía',
                'verbose_name_plural': 'Solicitudes a Fiscalía',
                'ordering': ['-creado_en'],
            },
        ),
    ]
