# Generated by Django 5.1.15 on 2026-08-02 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operativo', '0012_detective_actividades_legal'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedientecaso',
            name='codigo_caso',
            field=models.CharField(blank=True, help_text='Código de caso remitido por Fiscalía (ej. CAS-2026-0001).', max_length=40),
        ),
        migrations.AddField(
            model_name='expedientecaso',
            name='unidad',
            field=models.CharField(blank=True, default='Policía Judicial', help_text='Unidad / dependencia que remite o investiga el caso.', max_length=120),
        ),
    ]
