# Generated by Django 5.1.15 on 2026-08-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operativo', '0013_expediente_codigo_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidenciacaso',
            name='estado_custodia',
            field=models.CharField(choices=[('EN_CUSTODIA', 'En custodia'), ('LABORATORIO', 'En laboratorio'), ('FISCALIA', 'Remitida a Fiscalía'), ('ARCHIVO', 'Archivada'), ('BAJA', 'Dada de baja')], default='EN_CUSTODIA', max_length=20),
        ),
        migrations.AddField(
            model_name='evidenciacaso',
            name='sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
