# Generated by Django 5.1.15 on 2026-08-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operativo', '0014_evidencia_sha_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='involucradoexpediente',
            name='alias',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='involucradoexpediente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='involucradoexpediente',
            name='foto_bucket',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='involucradoexpediente',
            name='foto_content_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='involucradoexpediente',
            name='foto_nombre',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='involucradoexpediente',
            name='foto_object_key',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='involucradoexpediente',
            name='genero',
            field=models.CharField(choices=[('NO_ESPECIFICADO', 'No especificado'), ('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino'), ('OTRO', 'Otro')], default='NO_ESPECIFICADO', max_length=20),
        ),
        migrations.AddField(
            model_name='involucradoexpediente',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
