# Generated by Django 5.1.15 on 2026-08-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operativo', '0015_involucrado_perfil_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='involucradoexpediente',
            name='estado_civil',
            field=models.CharField(choices=[('NO_REGISTRADO', 'No registrado'), ('SOLTERO', 'Soltero/a'), ('CASADO', 'Casado/a'), ('DIVORCIADO', 'Divorciado/a'), ('VIUDO', 'Viudo/a'), ('UNION', 'Unión de hecho')], default='NO_REGISTRADO', max_length=20),
        ),
        migrations.AddField(
            model_name='involucradoexpediente',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
