# Generated by Django 5.1.15 on 2026-08-02 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operativo', '0016_involucrado_ocupacion_civil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.PositiveSmallIntegerField(help_text='Escala 1–5')),
                ('anotacion', models.TextField(blank=True)),
                ('periodo', models.CharField(blank=True, help_text='Etiqueta de periodo, ej. 2026-08 o Trimestre 3.', max_length=40)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('evaluador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_emitidas', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evaluación de supervisor',
                'verbose_name_plural': 'Evaluaciones de supervisores',
                'ordering': ['-creado_en'],
            },
        ),
    ]
