# Generated by Django 5.1.15 on 2026-08-02 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operativo', '0017_evaluacion_supervisor'),
        ('organizacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('PARTE_RECHAZADO', 'Parte rechazado'), ('PARTE_APROBADO', 'Parte aprobado'), ('EXPEDIENTE_ASIGNADO', 'Expediente asignado'), ('DISPOSICION_ZONA', 'Disposición de zona'), ('ALERTA', 'Alerta'), ('SISTEMA', 'Sistema')], default='SISTEMA', max_length=40),
        ),
        migrations.CreateModel(
            name='DisposicionZona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MEMORANDO', 'Memorando'), ('INSTRUCCION', 'Instrucción operativa'), ('DISPOSICION', 'Disposición directa'), ('COMUNICADO', 'Comunicado')], default='DISPOSICION', max_length=20)),
                ('prioridad', models.CharField(choices=[('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente / prioritaria')], default='ALTA', max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('cuerpo', models.TextField()),
                ('destinatarios_count', models.PositiveIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disposiciones_emitidas', to=settings.AUTH_USER_MODEL)),
                ('jurisdiccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disposiciones', to='organizacion.jurisdiction')),
            ],
            options={
                'verbose_name': 'Disposición de zona',
                'verbose_name_plural': 'Disposiciones de zona',
                'ordering': ['-creado_en'],
            },
        ),
    ]
