# Generated by Django 5.1.15 on 2026-08-08 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operativo', '0018_disposicion_zona_notif'),
        ('saas_core', '0001_saas_multitenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedientecaso',
            name='institucion',
            field=models.ForeignKey(blank=True, help_text='Aislamiento multi-tenant: hereda del detective / creador.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expedientes', to='saas_core.institucion'),
        ),
        migrations.AddField(
            model_name='parteaprehension',
            name='institucion',
            field=models.ForeignKey(blank=True, help_text='Aislamiento multi-tenant: hereda la institución del creador.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partes', to='saas_core.institucion'),
        ),
    ]
